### ISSUE TITLE
没有数据结构和里面的内容, 运行不起来! 能否帮忙提交, 谢谢!!!

### ISSUE THREAD

**Issue by dxf1122** [bosspen1/stock#17]
没有数据结构和里面的内容, 运行不起来!

    @Override
    public TradeMethod getByName(String name) {
        return jdbcTemplate.queryForObject("select id, name, url, state from trade_method where name = ?",
                BeanPropertyRowMapper.newInstance(TradeMethod.class), name);
    }

用到数据库里的URL去请求接口交易. 

谢谢!!!

**Comment by bosspen1** [comment]
文档和数据库表见wiki

注意: 把wiki clone下来就可以看到数据库表结构和部署和升级文档!!!
