### ISSUE TITLE
docker-compose集成存储

### ISSUE THREAD

**Issue by wangzhenhui1992** [bosspen1/stock#31]
能不能将mysql/redis这些要用到的，集成到docker-compose中去，并初始化创建数据库和表。。。这样可以一键启动整个项目。。。不需要再克隆wiki然后手动操作

**Comment by token01** [comment]
article content is very good advice

**Comment by bosspen1** [comment]
> 能不能将mysql/redis这些要用到的，集成到docker-compose中去，并初始化创建数据库和表。。。这样可以一键启动整个项目。。。不需要再克隆wiki然后手动操作

已经没有redis依赖了。现在就mysql了。 dockerfile修改了，更简单的，只要准备mysql了。 我晚点再弄mysql镜像

**Comment by crazydragon8888** [comment]
可以拉我进群吗？群满了 怎么才能进群呢？

**Comment by crazydragon8888** [comment]
> > 能不能将mysql/redis这些要用到的，集成到docker-compose中去，并初始化创建数据库和表。。。这样可以一键启动整个项目。。。不需要再克隆wiki然后手动操作
> 
> 已经没有redis依赖了。现在就mysql了。 dockerfile修改了，更简单的，只要准备mysql了。 我晚点再弄mysql镜像

大佬可以拉我进群吗 群已经满了200人了 有没有其他办法 或者能否直接加微信？

**Comment by bosspen1** [comment]
3400以下无更新计划
