### ISSUE TITLE
请问有均线的接口吗

### ISSUE THREAD

**Issue by DouglasWang168** [bosspen1/stock#4]
5，10，20，60，120均线接口请问有吗

**Comment by bosspen1** [comment]
东方财富的接口没去对接。&nbsp;但可以利用爬取的每日的数据是写这些接口




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"DouglasWang168"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月9日(星期六) 晚上10:39
收件人:&nbsp;"bosspen1/stock"<stock@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[bosspen1/stock] 请问有均线的接口吗 (#4)





 
5，10，20，60，120均线接口请问有吗

**Comment by bosspen1** [comment]
@bosspen1
