### ISSUE TITLE
又错过二维码了

### ISSUE THREAD

**Issue by fannianhao** [bosspen1/stock#42]

**Comment by dawn9117** [comment]
@bosspen1 大佬更新一波二维码

**Comment by bosspen1** [comment]
好了

**Comment by dawn9117** [comment]
大佬，进不去，提示 该群已开启进群验证只可通过邀请进群
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年12月18日 15:56 |
| 收件人 | bosspen1/stock ***@***.***> |
| 抄送人 | dawn9117 ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [bosspen1/stock] 又错过二维码了 (Issue #42) |

好了

**Comment by dawn9117** [comment]
@bosspen1 大佬，进不去，提示 该群已开启进群验证只可通过邀请进群
