### ISSUE TITLE
数据库初始化文件呢

### ISSUE THREAD

**Issue by hebingooo** [bosspen1/stock#6]
哥， 表结构呢？

**Comment by bosspen1** [comment]
在wiki里面。clone下来就可以看到了

**Comment by hebingooo** [comment]
@bosspen1 隐藏的真够深啊，clone下来看到了

**Comment by bosspen1** [comment]
readme里面写了，回头我标红一下------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;hebingooo&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年5月26日(星期二) 上午10:38
收件人:&nbsp;&quot;bosspen1/stock&quot;<stock@noreply.github.com&gt;;
抄送:&nbsp;&quot;Harry Zhang&quot;<240440056@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [bosspen1/stock] 数据库初始化文件呢 (#6)
