### ISSUE TITLE
TradeServiceImpl 的 update 方法 

### ISSUE THREAD

**Issue by vxinv** [bosspen1/stock#8]
@CachePut(value = StockConsts.CACHE_KEY_TRADE_USER, key = "#tradeUser.id")
    @Override
    public TradeUser update(TradeUser tradeUser) {
        tradeUserDao.update(tradeUser);
        return tradeUser;
    }

使用CachePut 是不是更合理一点

**Comment by vxinv** [comment]
ok

**Comment by bosspen1** [comment]
感谢提醒。 TradeUser 在这里里面有个变量是accountId是没有，不能直接写入缓存。 对于其他地方的，是用CachePut更加合理，本项目压力不是很大，所以写的时候大部分都是让缓存失效。
