### ISSUE TITLE
wiki中的sql dml_stock_master.sql 有错

### ISSUE THREAD

**Issue by Qin-K-Img** [bosspen1/stock#9]
这是ddl中robot建表语句
![image](https://user-images.githubusercontent.com/76505290/106372714-9f6aca00-63ad-11eb-9aa1-88be8c0f890a.png)

dml_stock_master.sql中导入数据，字段和值反了，导致导入出错
![image](https://user-images.githubusercontent.com/76505290/106372767-f96b8f80-63ad-11eb-83ff-5e26c44fd19a.png)

![image](https://user-images.githubusercontent.com/76505290/106372773-11431380-63ae-11eb-9549-258a24d9f38d.png)

**Comment by bosspen1** [comment]
谢谢指正，已经修改。
